valve_analitics_webapp: add project files
nikitazavadsky/valve_analytics_webapp pull request #1
Opened 2022-12-19 17:29 UTC by PashaDem

2022-12-19 20:42 UTC, mosey20000 commented on valve_analytics_webapp/settings.py
> +SECRET_KEY = "django-insecure-nxijwdxi-cfzdg@yx1a)otit&jrgx8us-ni+hla@ks91*mrblt"
hide secret key to .env and create .env.tmp

2022-12-20 16:50 UTC, PashaDem commented on valve_analytics_webapp/settings.py
> +SECRET_KEY = "django-insecure-nxijwdxi-cfzdg@yx1a)otit&jrgx8us-ni+hla@ks91*mrblt"
Updated

2022-12-23 23:43 UTC, Vladgasik requested changes
Remove auto-generated comments in `settings.py`

2022-12-24 11:35 UTC, PashaDem commented
> Remove auto-generated comments in `settings.py`

Updated

2022-12-24 14:06 UTC, Vladgasik submitted a review, later dismissed

2022-12-24 17:12 UTC, Vladgasik commented on valve_analytics_webapp/settings.py
> +    "rest_framework",
Use this approach, please

![image](https://user-images.githubusercontent.com/62799353/209445375-c7dae0a4-b667-469e-8844-f205940ca837.png)

2022-12-24 19:17 UTC, PashaDem commented on valve_analytics_webapp/settings.py
> +    "rest_framework",
Updated

2022-12-27 14:50 UTC, Vladgasik approved these changes

2022-12-27 19:04 UTC, merged