Env Setup: added poetry description
nikitazavadsky/valve_analytics_webapp pull request #4
Opened 2022-12-21 21:08 UTC by Vladgasik

2022-12-21 21:34 UTC, nikitazavadsky requested changes

2022-12-21 21:34 UTC, nikitazavadsky commented on README.md
> +    curl -sSL https://install.python-poetry.org | python3 -
Could you please then move installation process to single bash script and update documentation accordingly?

Leave information about action that will be done in terms of script run somehow

2022-12-21 22:00 UTC, Vladgasik commented on README.md
> +    curl -sSL https://install.python-poetry.org | python3 -
what do you mean by `move installation process to single bash script`?
should I create bash script `install.sh` with content like?
```
curl -sSL https://install.python-poetry.org | python3 -
poetry install
poetry run pre-commit install

2022-12-21 22:08 UTC, nikitazavadsky commented on README.md
> +    curl -sSL https://install.python-poetry.org | python3 -
Yep

2022-12-22 13:20 UTC, nikitazavadsky approved these changes

2022-12-22 13:21 UTC, merged