Dockerization of the app
nikitazavadsky/valve_analytics_webapp pull request #6
Opened 2023-01-03 22:48 UTC by PashaDem

2023-01-07 22:40 UTC, Vladgasik commented on docker-compose.yml
> +    image: postgres:15
We could use alpine version

2023-01-07 22:41 UTC, Vladgasik commented on docker-compose.yml
> +    command: python manage.py runserver 0.0.0.0:8000
we'll need to do something like this (write our own create_superuser command)
command: bash -c "python manage.py migrate && python manage.py create_superuser  && python manage.py runserver 0.0.0.0:8000"

2023-01-07 22:44 UTC, Vladgasik commented on docker-compose.yml
> +    depends_on:
we'll need to add here `restart: on-failure`, because when we try to apply migrations, when DB container is not running WEB container will fail

2023-01-07 22:44 UTC, Vladgasik commented on Dockerfile
> +ENV PIP_DISABLE_PIP_VERSION_CHECK 1
what purpose of this one?

2023-01-07 22:45 UTC, Vladgasik commented on Dockerfile
> +ENV PYTHONDONTWRITEBYTECODE 1
do we need it?

2023-01-07 22:46 UTC, Vladgasik commented on pyproject.toml
> +psycopg = "^3.1.7"
```suggestion
```

2023-01-07 22:48 UTC, Vladgasik requested changes
And we already have <feature 1> commit in repo

2023-01-07 23:04 UTC, PashaDem commented on docker-compose.yml
> +    image: postgres:15
Why? Because it is the version that takes the minimum size?

2023-01-13 00:01 UTC, PashaDem commented
> And we already have <feature 1> commit in repo

Do you mean the commit from the branch that was merged?

2023-01-13 00:03 UTC, PashaDem commented on Dockerfile
> +ENV PIP_DISABLE_PIP_VERSION_CHECK 1
This variable stops the output messaging that there is newer version of pip. I think that I'll remove it because we use poetry

2023-01-13 00:05 UTC, PashaDem commented on Dockerfile
> +ENV PYTHONDONTWRITEBYTECODE 1
the second env-var prevents python from generating .pyc files inside the container. It only makes our local repo's cleaner, but it is ignored when pushing to git, so I'll remove it too.

2023-01-13 00:56 UTC, PashaDem commented on docker-compose.yml
> +    image: postgres:15
Updated

2023-01-13 00:58 UTC, PashaDem commented on docker-compose.yml
> +    command: python manage.py runserver 0.0.0.0:8000
Updated, but I haven't created custom superuser command, I just hardcoded createsuperuser with parameters I've added to the .env file. I think It is nice idea to add the description of env vars in README.

2023-01-13 00:58 UTC, PashaDem commented on docker-compose.yml
> +    depends_on:
Updated

2023-01-13 00:59 UTC, PashaDem commented on Dockerfile
> +ENV PIP_DISABLE_PIP_VERSION_CHECK 1
Updated

2023-01-13 00:59 UTC, PashaDem commented on Dockerfile
> +ENV PYTHONDONTWRITEBYTECODE 1
Updated

2023-01-13 22:16 UTC, Vladgasik commented on docker-compose.yml
> +    depends_on:
I'm sure, that we can do just `createsuperuser --no-input` and its gonna give us some default superuser name and passwd

2023-01-13 22:18 UTC, Vladgasik commented on docker-compose.yml
> +    command: bash -c "python manage.py migrate && python manage.py createsuperuser --username ${SUPERUSERUSERNAME} --email ${SUPERUSEREMAIL} --no-input && python manage.py runserver 0.0.0.0:8000"
I'm sure, that we can do just createsuperuser --no-input and its gonna give us some default superuser name and passwd

2023-01-13 22:18 UTC, Vladgasik commented on docker-compose.yml
> +      - dev.env
Let's rename it into `.env`

2023-01-13 22:19 UTC, Vladgasik commented on valve_analytics_webapp/settings.py
> +        "PORT": 5432,
Use env vars here and in docker port mapping too

2023-01-14 00:16 UTC, PashaDem commented on docker-compose.yml
> +      - dev.env
Last time you said me to create two .env files - one for development and another fake one to push in repo. What have changed? If we will change it into .env, may be I should add some info in the README to note what env vars the developer should override in his env-file?

2023-01-14 01:06 UTC, PashaDem commented on docker-compose.yml
> +    command: bash -c "python manage.py migrate && python manage.py createsuperuser --username ${SUPERUSERUSERNAME} --email ${SUPERUSEREMAIL} --no-input && python manage.py runserver 0.0.0.0:8000"
1) No, you're wrong. Django won't provide us with some default pass or login, we have to declare them by ourselves as env-vars. But then raises another problem: every time we will up the container, it will try to create the superuser with the same username, so the django app will drop with the exit code -1 which will generate the reloading of the server and so on. It'll run in recursion.
!!! The same problem was and with the my version(where I hardcode credentials in the command), but I haven't seen them.
The decision I see now - not to createsuperuser while initializing project. Another one decision is to stop using volumes, but I am against of this.

2023-01-14 01:29 UTC, PashaDem commented on valve_analytics_webapp/settings.py
> +        "PORT": 5432,
Updated

2023-01-14 10:00 UTC, PashaDem commented on docker-compose.yml
> +    command: bash -c "python manage.py migrate && python manage.py createsuperuser --username ${SUPERUSERUSERNAME} --email ${SUPERUSEREMAIL} --no-input && python manage.py runserver 0.0.0.0:8000"
Updated

2023-01-14 12:14 UTC, Vladgasik commented on docker-compose.yml
> +      - dev.env
Exactly, see this readme https://github.com/MargitStar/MusicShop

2023-01-16 08:05 UTC, PashaDem commented on docker-compose.yml
> +      - dev.env
Updated

2023-01-20 18:15 UTC, PashaDem commented
> And we already have <feature 1> commit in repo

Updated

2023-01-27 08:59 UTC, closed without merging